# -*- coding: utf-8 -*-
"""Advanced Programming in Finance_GANs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_d7Nyxz8DWnX47XWUnaEfbfK51NzbIao

# Library
"""

import numpy as np
import pandas as pd

import io, os, sys

from google.colab import drive
drive.mount('/content/gdrive/')

import time
import datetime
from dateutil.parser import parse

import seaborn as sns

import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.decomposition import PCA

import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

import xgboost as xgb
from sklearn.metrics import accuracy_score

!pip install python-utils
!pip install mxnet

from mxnet import nd, autograd, gluon
from mxnet.gluon import nn, rnn
from mxnet.gluon import block
import mxnet as mx

import warnings
warnings.filterwarnings("ignore")

context = mx.cpu()
model_ctx = mx.cpu()
mx.random.seed(1719)

"""# Data"""

def parser(x):
    return datetime.datetime.strptime(x,'%Y-%m-%d')

my_path = "/content/gdrive/My Drive/Advance Programming in Finance/"
data_path = os.path.join(my_path, 'VAEdata.csv')

dataset = pd.read_csv(data_path, header = 0, parse_dates = [0], date_parser = parser)

"""# Auto Encoders"""



"""# Generator: LSTM and GRU"""



"""# Discriminator: CNNs"""

